name: WormholeXTremeWorlds
main: de.luricos.bukkit.worlds.WormholeXTremeWorlds
version: 0.5
author: alron
softdepend: [Permissions, Help]
description: >
             Wormhole X-Treme Worlds! World management for Wormhole X-Treme!
             
commands:
  wxw:
    description: Manage Worlds via Wormhole X-Treme Worlds
    usage: |
            Travel Commands:
            /<command> [ go <world> | spawn ]
            Info Commands:
            /<command> [ list | info <world>]
            Admin Commands:
            /<command> [create | remove | modify | setspawn | load] <args>
            All commands requiring arguments can be called without args for command specific help.
